Milestone 3: Added React redux
prg-04/bookstore_cms pull request #3
Opened 2023-08-22 14:48 UTC by prg-04

### I have done the following to reach this milestone:

- [ ] Wrapped my <App> with the <Provider> component from react-redux
- [ ] Passed my configured store into the <Provider>
- [ ] Created an initialState variable for my booksSlice.
- [ ] Displayed my books, received from the slice, in a reusable component
- [ ] Dispatched actions using useDispatch
- [ ] Added a <Button> component, which includes:
  - [ ] An event handler that adds a book to the books array (with attributes id, title and author)
- [ ] Add a <Button> component, which includes:
  - [ ] An event handler that removes a book from the books array (by id)

2023-08-22 18:20 UTC, wayungi requested changes
Hi @prg-04 , 

![image](https://user-images.githubusercontent.com/99656687/234198503-c41d0396-d5b0-4466-8ed1-959de33796fa.png)


**Congratulations on the good job done so far!** 🤝 

There are some issues that you still need to work on to go to the next project but you are almost there! 😄 

## Highlights ⚡ ⚡ 
- [ ] All linter checks passing ✔️ 
- [ ] Good commit messages ✔
- [ ]  Correct Git flow ✔️ 
- [ ] Descriptive PR body ✔️ 

## Required Changes ♻️
_Check the comments under the review._
- [ ] Please ensure that you can add and remove books in the application 😄 
## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-08-22 18:20 UTC, wayungi commented on src/components/Home.jsx
> +      /> */}
- [ ] Please do not commit old pieces of code as inline comments. They will make your project look messy. If you need to review a previous version of your code, you can always use git history. Kindly delete all instances of unused code left as comments 🤝

2023-08-22 18:20 UTC, wayungi commented on src/redux/book/bookSlice.js
> +});
- [OPTIONAL] While immer library is used behind the scene to  apply the changes in an immutable manner, for the sake of practice, I suggest you write immutable logic in the reducer. 😄

2023-08-22 18:20 UTC, wayungi commented on src/components/Form.jsx
- [ ] Please  make sure that the Form component has local state for title and author, which is updated through the onChange event. Please delete line 14..16 in favor of the approach below. The code snippets below should guide you. 👍🏾 

```
function Form() {
  const [title, setTitle] = useState("")
  const [author, setAuthor] = useState("")

```

- [ ] Please add onchange event listeners on the input fields on line 38 & 39 😸 
```
 <input className="form__input" type="text" placeholder="Book title" onChange= {(e) =setTitle(e.target.value)} />
 <input className="form__input" type="text" placeholder="Author"  onChange= {(e) =setTitle(e.target.value)}/>
 ```
 
 - [ ] Please also include an onClick event handler on your button to add the book to the books array. Note that this is a project requirement to implement it using this approach 🦅 
 
 ```
      <Button onClick={() => dispatch(addBook({ title, author }))}>
        Add book
      </Button>
```

2023-08-22 18:20 UTC, wayungi commented on src/components/Book.jsx
> +          ))}
- [ ] Good add adding all the buttons required. Please note that the **remove button** an event handler to **remove** a book from the `books` array (with the *id* attribute). 

```
<Button onClick={() => dispatch(removeBook(id))}>Remove</Button>`
```

2023-08-24 19:09 UTC, VICTOR-CHUKWU approved these changes
Hi @prg-04 , 
# STATUS: APPROVED! 🥇 💯 
![done](https://media.giphy.com/media/l1uga8ObPBnIBoXUQ/giphy.gif)

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights
- [ ] All linters passed
- [ ] redux used correctly in components

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-08-24 19:09 UTC, VICTOR-CHUKWU commented on src/components/Form.jsx
> +  const [author, setAuthor] = useState('');
- [ ] [OPTIONAL] you can actually use one state to manage all your input values like 
```
 const [input, setInput] = useState({
author: '',
title: ''
});
```

2023-08-24 19:29 UTC, merged